### ISSUE TITLE
ValueError: Width and Height must be > 0

### ISSUE THREAD

**Issue by ashokbugude** [ishwarsawale/real-time-face-recognition-with-facenet#4]
I am trying to run 
`python aligndata_first.py`

I get below error for one of the images
```
Traceback (most recent call last):
  File "aligndata_first.py", line 95, in <module>
    scaled_temp = misc.imresize(cropped_temp, (image_size, image_size), interp='bilinear')
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 478, in imresize
    im = toimage(arr, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 368, in toimage
    image = Image.frombytes(mode, shape, strdata)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2060, in frombytes
    _check_size(size)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2001, in _check_size
    raise ValueError("Width and Height must be > 0")
ValueError: Width and Height must be > 0
```
Can I know how to ignore the error for this particular image and proceed with next image

**Comment by ashokbugude** [comment]
Resolved it by checking the dimensions of cropped_temp
